merge all develop changes to master to upgrade release version  (#222)
merge all develop changes to master to upgrade release version  (#222)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -56,6 +56,50 @@ jobs:
           name: Compile
           command: ./gradlew clean compileJava compileTestJava
       - sonarcloud/scan
+      - run:
+          name: Check Quality Gate
+          command: |
+                    REPORT_PATH="/home/circleci/project/.scannerwork/report-task.txt"
+                    CE_TASK_ID_KEY="ceTaskId="
+                    SONAR_INSTANCE="https://sonarcloud.io"
+                    SLEEP_TIME=5
+                    # get the compute engine task id
+                    ce_task_id=$(cat $REPORT_PATH | grep $CE_TASK_ID_KEY | cut -d'=' -f2)
+                    echo "Using task id of ${ce_task_id}"
+                    if [ -z "$ce_task_id" ]; then
+                       echo "No task id found"
+                       exit 1
+                    fi
+                    # grab the status of the task
+                    # if CANCELLED or FAILED, fail the Build
+                    # if SUCCESS, stop waiting and grab the analysisId
+                    wait_for_success=true
+                    while [ "${wait_for_success}" = "true" ]
+                    do
+                      ce_status=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/ce/task?id=${ce_task_id} | jq -r .task.status)
+                      echo "Status of SonarQube task is ${ce_status}"
+                      if [ "${ce_status}" = "CANCELLED" ]; then
+                        echo "SonarQube Compute job has been cancelled - exiting with error"
+                        exit 504
+                      fi
+                      if [ "${ce_status}" = "FAILED" ]; then
+                        echo "SonarQube Compute job has failed - exit with error"
+                        exit 500
+                      fi
+                      if [ "${ce_status}" = "SUCCESS" ]; then
+                        wait_for_success=false
+                      fi
+                      sleep "${SLEEP_TIME}"
+                    done
+                    ce_analysis_id=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/ce/task?id=$ce_task_id | jq -r .task.analysisId)
+                    echo "Using analysis id of ${ce_analysis_id}"
+                    # get the status of the quality gate for this analysisId
+                    qg_status=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/qualitygates/project_status?analysisId="${ce_analysis_id}" | jq -r .projectStatus.status)
+                    echo "Quality Gate status is ${qg_status}"
+                    if [ "${qg_status}" != "OK" ]; then
+                      echo "Quality gate is not OK - exiting with error"
+                      exit 1
+                    fi
 
   docker-build:
     executor: docker
@@ -94,7 +138,7 @@ jobs:
             - ./image-8.tar
             - ./image.tar
             - ./latest.tar
-  
+
   deploy-cxflow:
     executor: aws-eks/python3
     parameters:
@@ -126,26 +170,17 @@ jobs:
           cluster-name: << parameters.cluster-name >>
           install-kubectl: true
       - run:
-          name: Create namespace
-          command: |
-            export NAMESPACE_EXISTS=$(kubectl get namespaces | grep << parameters.namespace >>)
-            if [[ ${NAMESPACE_EXISTS} ]]; then echo "Namespace already exists"; else kubectl create namespace << parameters.namespace >>; fi
-      - run:
           name: Change appVersion
           command: |
-            sed -i "s/appVersion:[[:space:]]*.*/appVersion: ${CIRCLE_SHA1::7}/g" ./helm/cxflow/Chart.yaml
+            sed -i "s/appVersion:[[:space:]]*.*/appVersion: '${CIRCLE_SHA1::7}'/g" ./helm/cxflow/Chart.yaml
       - helm/install-helm-client:
           version: << parameters.version >>
       - run:
-          name: Install cxflow service on cluster 
+          name: Install cxflow service on cluster
           command: |
-            helm upgrade --install --atomic --namespace << parameters.namespace >> << parameters.release-name >> \
-              --set cxflow.checkmarxUsername=${CHECKMARX_USERNAME} \
-              --set cxflow.checkmarxPassword=${CHECKMARX_PASSWORD} \
-              --set cxflow.checkmarxBaseUrl=${CHECKMARX_BASE_URL} \
+            helm upgrade --install --atomic --create-namespace --namespace << parameters.namespace >> << parameters.release-name >> \
               --set cxflow.githubToken=${GITHUB_TOKEN} \
               --set cxflow.githubWebhookToken=${GITHUB_WEBHOOK_TOKEN} \
-              --set cxflow.checkmarxClientSecret=${CHECKMARX_CLIENT_SECRET} \
               --set cxflow.jiraUrl=${JIRA_URL} \
               --set cxflow.jiraUserName=${JIRA_USERNAME} \
               --set cxflow.jiraToken=${JIRA_TOKEN} \
@@ -205,7 +240,7 @@ jobs:
     docker:
       - image: "circleci/openjdk:8-jdk"
     steps:
-      - checkout 
+      - checkout
       - run:
           name: Run Integration Tests
           command: |
@@ -221,7 +256,7 @@ jobs:
           path: ~/test-results
       - store_artifacts:
           path: ~/test-results/junit
-  
+
   cleanup:
     executor: aws-eks/python3
     parameters:
@@ -253,7 +288,7 @@ jobs:
           command: kubectl delete namespace << parameters.namespace >>
       - store_artifacts:
           path: ~/application-logs
-      
+
   docker-push-stable:
     executor: docker
     steps:
@@ -301,9 +336,10 @@ workflows:
           context: sonarcloud
           filters:
             branches:
-              only: 
+              only:
                 - develop
                 - /pr-.*/
+                - /pr .*/
                 - sonar
   build_deploy:
     jobs:
@@ -316,6 +352,7 @@ workflows:
               only: 
                 - develop
                 - /pr-.*/
+                - /pr .*/
       - component-tests:
           requires:
             - build
@@ -324,12 +361,13 @@ workflows:
           chart: ./helm/cxflow
           namespace: cxflow-${CIRCLE_SHA1::7}
           release-name: cxflow-${CIRCLE_SHA1::7}
-          version: v3.1.1
+          version: v3.2.1
           filters:
             branches:
               only: 
                 - develop
                 - /pr-.*/
+                - /pr .*/
           requires:
             - docker-build
             - component-tests
@@ -339,6 +377,7 @@ workflows:
               only: 
                 - develop
                 - /pr-.*/
+                - /pr .*/
           requires:
             - deploy-cxflow
       - integration-tests:
@@ -347,14 +386,14 @@ workflows:
       - docker-push-stable:
           filters:
             branches:
-              only: develop
+              only: master
           requires:
             - e2e-tests
             - integration-tests
       - publish-github-release:
           filters:
             branches:
-              only: develop
+              only: master
           requires:
             - e2e-tests
             - integration-tests
@@ -362,12 +401,13 @@ workflows:
           cluster-name: eks-cxflow-ci
           namespace: cxflow-${CIRCLE_SHA1::7}
           release-name: cxflow-${CIRCLE_SHA1::7}
-          version: v3.1.1
+          version: v3.2.1
           filters:
             branches:
               only: 
                 - develop
                 - /pr-.*/
+                - /pr .*/
           requires:
             - e2e-tests
             - integration-tests
