Changing the way sonar scan is executed to avoid problems with certificate on the ubuntu machine to connect to SonarCloud. This way is actually the recommended way by SonarCloud

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -49,58 +49,57 @@ jobs:
           path: ~/test-results/junit
 
   sonar:
-    machine:
-      image: ubuntu-1604:201903-01
+    docker:
+      - image: circleci/openjdk:8-jdk
     steps:
       - checkout
       - run:
-          name: Compile
-          command: ./gradlew clean compileJava compileTestJava
-      - sonarcloud/scan
+          name: Analyze by SonarCloud
+          command: ./gradlew clean compileJava compileTestJava sonarqube -x test --info
       - run:
           name: Check Quality Gate
           command: |
-                    REPORT_PATH="/home/circleci/project/.scannerwork/report-task.txt"
-                    CE_TASK_ID_KEY="ceTaskId="
-                    SONAR_INSTANCE="https://sonarcloud.io"
-                    SLEEP_TIME=5
-                    # get the compute engine task id
-                    ce_task_id=$(cat $REPORT_PATH | grep $CE_TASK_ID_KEY | cut -d'=' -f2)
-                    echo "Using task id of ${ce_task_id}"
-                    if [ -z "$ce_task_id" ]; then
-                       echo "No task id found"
-                       exit 1
-                    fi
-                    # grab the status of the task
-                    # if CANCELLED or FAILED, fail the Build
-                    # if SUCCESS, stop waiting and grab the analysisId
-                    wait_for_success=true
-                    while [ "${wait_for_success}" = "true" ]
-                    do
-                      ce_status=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/ce/task?id=${ce_task_id} | jq -r .task.status)
-                      echo "Status of SonarQube task is ${ce_status}"
-                      if [ "${ce_status}" = "CANCELLED" ]; then
-                        echo "SonarQube Compute job has been cancelled - exiting with error"
-                        exit 504
-                      fi
-                      if [ "${ce_status}" = "FAILED" ]; then
-                        echo "SonarQube Compute job has failed - exit with error"
-                        exit 500
-                      fi
-                      if [ "${ce_status}" = "SUCCESS" ]; then
-                        wait_for_success=false
-                      fi
-                      sleep "${SLEEP_TIME}"
-                    done
-                    ce_analysis_id=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/ce/task?id=$ce_task_id | jq -r .task.analysisId)
-                    echo "Using analysis id of ${ce_analysis_id}"
-                    # get the status of the quality gate for this analysisId
-                    qg_status=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/qualitygates/project_status?analysisId="${ce_analysis_id}" | jq -r .projectStatus.status)
-                    echo "Quality Gate status is ${qg_status}"
-                    if [ "${qg_status}" != "OK" ]; then
-                      echo "Quality gate is not OK - exiting with error"
-                      exit 1
-                    fi
+            REPORT_PATH="/home/circleci/project/build/sonar/report-task.txt"
+            CE_TASK_ID_KEY="ceTaskId="
+            SONAR_INSTANCE="https://sonarcloud.io"
+            SLEEP_TIME=5
+            # get the compute engine task id
+            ce_task_id=$(cat $REPORT_PATH | grep $CE_TASK_ID_KEY | cut -d'=' -f2)
+            echo "Using task id of ${ce_task_id}"
+            if [ -z "$ce_task_id" ]; then
+               echo "No task id found"
+               exit 1
+            fi
+            # grab the status of the task
+            # if CANCELLED or FAILED, fail the Build
+            # if SUCCESS, stop waiting and grab the analysisId
+            wait_for_success=true
+            while [ "${wait_for_success}" = "true" ]
+            do
+              ce_status=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/ce/task?id=${ce_task_id} | jq -r .task.status)
+              echo "Status of SonarQube task is ${ce_status}"
+              if [ "${ce_status}" = "CANCELLED" ]; then
+                echo "SonarQube Compute job has been cancelled - exiting with error"
+                exit 504
+              fi
+              if [ "${ce_status}" = "FAILED" ]; then
+                echo "SonarQube Compute job has failed - exit with error"
+                exit 500
+              fi
+              if [ "${ce_status}" = "SUCCESS" ]; then
+                wait_for_success=false
+              fi
+              sleep "${SLEEP_TIME}"
+            done
+            ce_analysis_id=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/ce/task?id=$ce_task_id | jq -r .task.analysisId)
+            echo "Using analysis id of ${ce_analysis_id}"
+            # get the status of the quality gate for this analysisId
+            qg_status=$(curl -s -u "${SONAR_TOKEN}": "${SONAR_INSTANCE}"/api/qualitygates/project_status?analysisId="${ce_analysis_id}" | jq -r .projectStatus.status)
+            echo "Quality Gate status is ${qg_status}"
+            if [ "${qg_status}" != "OK" ]; then
+              echo "Quality gate is not OK - exiting with error"
+              exit 1
+            fi
 
   docker-build:
     executor: docker
@@ -324,7 +323,6 @@ jobs:
             ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -n ${VERSION} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/libs/
 
 orbs:
-  sonarcloud: sonarsource/sonarcloud@1.0.1
   aws-eks: circleci/aws-eks@0.2.6
   kubernetes: circleci/kubernetes@0.4.0
   helm: circleci/helm@0.2.3
@@ -351,7 +349,7 @@ workflows:
             - build
           filters:
             branches:
-              only: 
+              only:
                 - master
                 - develop
                 - /pr-.*/
@@ -367,7 +365,7 @@ workflows:
           version: v3.2.1
           filters:
             branches:
-              only: 
+              only:
                 - master
                 - develop
                 - /pr-.*/
@@ -378,7 +376,7 @@ workflows:
       - e2e-tests:
           filters:
             branches:
-              only: 
+              only:
                 - master
                 - develop
                 - /pr-.*/
@@ -409,7 +407,7 @@ workflows:
           version: v3.2.1
           filters:
             branches:
-              only: 
+              only:
                 - master
                 - develop
                 - /pr-.*/
