Configuration of sonar cloud to validate the sonar gate

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -55,9 +55,54 @@ jobs:
       - run:
           name: Compile
           command: ./gradlew clean compileJava compileTestJava
-      - sonarcloud/scan_with_gradle:
-          main_branch: develop
-          gradle_task: sonarqube -x test
+      - sonarcloud/scan
+      - run:
+          name: Check Quality Gate
+          command: |
+                    REPORT_PATH=".build/sonar/report-task.txt"
+                    CE_TASK_ID_KEY="ceTaskId="
+                    SONAR_INSTANCE="https://sonarcloud.io"
+                    SLEEP_TIME=5
+                    # get the compute engine task id
+                    ce_task_id=$(cat $REPORT_PATH | grep $CE_TASK_ID_KEY | cut -d'=' -f2)
+                    echo "Using task id of ${ce_task_id}"
+                    if [ -z "$ce_task_id" ]; then
+                       echo "No task id found"
+                       exit 1
+                    fi
+                    # grab the status of the task
+                    # if CANCELLED or FAILED, fail the Build
+                    # if SUCCESS, stop waiting and grab the analysisId
+                    wait_for_success=true
+                    while [ "${wait_for_success}" = "true" ]
+                    do
+                      ce_status=$(curl -s -u "${SONAR_AUTH_TOKEN}": "${SONAR_INSTANCE}"/api/ce/task?id=${ce_task_id} | jq -r .task.status)
+                      echo "Status of SonarQube task is ${ce_status}"
+                      if [ "${ce_status}" = "CANCELLED" ]; then
+                        echo "SonarQube Compute job has been cancelled - exiting with error"
+                        exit 504
+                      fi
+                      if [ "${ce_status}" = "FAILED" ]; then
+                        echo "SonarQube Compute job has failed - exit with error"
+                        exit 500
+                      fi
+                      if [ "${ce_status}" = "SUCCESS" ]; then
+                        wait_for_success=false
+                      fi
+                      sleep "${SLEEP_TIME}"
+                    done
+                    ce_analysis_id=$(curl -s -u $SONAR_AUTH_TOKEN:
+                    $SONAR_INSTANCE/api/ce/task?id=$ce_task_id | jq -r .task.analysisId)
+                    echo "Using analysis id of ${ce_analysis_id}"
+                    # get the status of the quality gate for this analysisId
+                    qg_status=$(curl -s -u $SONAR_AUTH_TOKEN:
+                    $SONAR_INSTANCE/api/qualitygates/project_status?analysisId="${ce_analysis_id}"
+                    | jq -r .projectStatus.status)
+                    echo "Quality Gate status is ${qg_status}"
+                    if [ "${qg_status}" != "OK" ]; then
+                      echo "Quality gate is not OK - exiting with error"
+                      exit 1
+                    fi
 
   docker-build:
     executor: docker
@@ -290,7 +335,7 @@ jobs:
             ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -n ${VERSION} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/libs/
 
 orbs:
-  sonarcloud: extendaretail/sonarcloud@0.0.2
+  sonarcloud: sonarsource/sonarcloud@1.0.1
   aws-eks: circleci/aws-eks@0.2.6
   kubernetes: circleci/kubernetes@0.4.0
   helm: circleci/helm@0.2.3
@@ -308,10 +353,6 @@ workflows:
                 - /pr-.*/
                 - /pr .*/
                 - sonar
-      - sonarcloud/check_quality_gate:
-          context: sonarcloud
-          requires:
-            - sonar
   build_deploy:
     jobs:
       - build
